#! bash

touch output.file

# write task information to a (yaml) file
cat <<-END_TASK > task.yaml
'${task.process}':
  task:
    '${task.index}':
      params:
        sample: $sample
      meta:
        workDir: `pwd`
  process:
    ext: []
    versions:
      analysis tool: `analysis_tool --version`
      parsing tool: `parsing_tool -v`
END_TASK
