#! Rscript

library(magrittr)
library(scampr)

log_message('making a connection to biomart', level='main')

task.process <- "${task.process}"
task.index <- "${task.index}"

list(nvalues = "$nvalues") |>
    assign_and_record_task()

data.frame(x=rnorm(n=nvalues), y=rnorm(n=nvalues)) |>
    saveRDS(file='data.rds')
